// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa">
      <head />
      <body>{children}</body>
    </html>
  );
}
